export const Users = [
  {
    id: 1,
    profilePicture: "https://i.pravatar.cc/150?img=1",
    username: "Safak Kocaoglu",
  },
  {
    id: 2,
    profilePicture: "https://i.pravatar.cc/150?img=2",
    username: "Janell Shrum",
  },
  {
    id: 3,
    profilePicture: "https://i.pravatar.cc/150?img=3",
    username: "Alex Durden",
  },
  {
    id: 4,
    profilePicture: "https://i.pravatar.cc/150?img=4",
    username: "Dora Hawks",
  },
  {
    id: 5,
    profilePicture: "https://i.pravatar.cc/150?img=5",
    username: "Thomas Holden",
  },
  {
    id: 6,
    profilePicture: "https://i.pravatar.cc/150?img=6",
    username: "Shirley Beauchamp",
  },
  {
    id: 7,
    profilePicture: "https://i.pravatar.cc/150?img=7",
    username: "Travis Bennett",
  },
  {
    id: 8,
    profilePicture: "https://i.pravatar.cc/150?img=8",
    username: "Kristen Thomas",
  },
  {
    id: 9,
    profilePicture: "https://i.pravatar.cc/150?img=9",
    username: "Gary Duty",
  },
  {
    id: 10,
    profilePicture: "https://i.pravatar.cc/150?img=10",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "https://picsum.photos/400/300?random=1",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "https://picsum.photos/400/300?random=2",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "https://picsum.photos/400/300?random=3",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "https://picsum.photos/400/300?random=4",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "https://picsum.photos/400/300?random=5",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "https://picsum.photos/400/300?random=6",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "https://picsum.photos/400/300?random=7",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "https://picsum.photos/400/300?random=8",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "https://picsum.photos/400/300?random=9",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "https://picsum.photos/400/300?random=10",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];